Rename classes folder to api
RebelToolbox/RebelDocumentation pull request #10
Opened 2024-01-26 10:23 UTC by madmiraal

To better reflect that the folder contains the Rebel Engine API ReST files, this PR renames the `classes` folder to `api`.

In addition, it updates the documentation to reflect the name change along with the corresponding understanding that it's an API. Furthermore, it includes updates the documentation to reflect the changes introduced by RebelToolbox/RebelEngine#26.

2024-01-26 12:52 UTC, DanielaOrtner requested changes
Could you please check the feedback? 

Thank you

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/code_style_guidelines.rst
> +the :ref:`API Documentation <doc_updating_the_api_documentaton>`
I believe there is a typo in the last word of the line: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/contributing_to_the_documentation.rst
> +.. warning:: The API documenation source files are in the `Rebel Engine
Should the word "documenation" be "documentation" instead?

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/contributing_to_the_documentation.rst
> +             :ref:`doc_updating_the_api_documentaton`.
I believe there is a typo in the last word of the line: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/contributing_to_the_documentation.rst
> +See :ref:`doc_updating_the_api_documentaton` for details.
I believe there is a typo in the word: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/documentation_guidelines.rst
> +             :ref:`doc_updating_the_api_documentaton`.
I believe there is a typo in the last word of the line: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/documentation_guidelines.rst
> +             online docs. Read more here: :ref:`doc_updating_the_api_documentaton`.
I believe there is a typo in the last word of the line: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/index.rst
> +API Documentaiton
Maybe this should be "Documentation" instead of "Documentaiton"?

2024-01-26 12:52 UTC, DanielaOrtner commented on contributing/ways_to_contribute.rst
> +  See :ref:`doc_updating_the_api_documentaton` and
I believe there is a typo in the word: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on development/cpp/custom_modules_in_cpp.rst
> +Edit the file(s) following :ref:`doc_updating_the_api_documentaton` and recompile the engine.
I believe there is a typo in the word: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on tutorials/networking/http_request_class.rst
> +For more information on parsing JSON, see the API documentations for :ref:`JSON <class_JSON>` and :ref:`JSONParseResult <class_JSONParseResult>`.
Should this really be the plural "documentations"?

2024-01-26 12:52 UTC, DanielaOrtner commented on tutorials/ui/bbcode_in_richtextlabel.rst
> +:ref:`XML source of the API documentation <doc_updating_the_api_documentaton>`.
I believe there is a typo in the word: "documentaton"

2024-01-26 12:52 UTC, DanielaOrtner commented on about/introduction.rst
> +  :ref:`doc_updating_the_api_documentaton` for details.
I believe there is a typo in the word: "documentaton"

2024-01-26 17:53 UTC, madmiraal commented
Good spot! We clearly need to work out why the spell checker didn't pick these up.

2024-01-27 08:54 UTC, madmiraal commented
Corrected all the incorrect spellings of documentation.

I'll submit a separate PR to address the problem with the spell checker not working.

2024-01-27 09:01 UTC, madmiraal commented
Updated to include changes to the Rebel Engine API introduced by RebelToolbox/RebelEngine#26.

2024-01-27 16:45 UTC, DanielaOrtner approved these changes
Thank you for checking the spelling issues and fixing them.
All looks good now :)

2024-01-27 16:45 UTC, merged